### ISSUE TITLE
Bug : Wrong delay for Private messages

### ISSUE THREAD

**Issue by Ezergil** [TelegramBotExtensions/TelegramBotClients#6]
Hey, @MihaZupan !
I made an example here https://github.com/Ezergil/TestRateLimitedBotClient
As you could see by program output - everything works fine when there are only messages to user (1 second delay between) and to group (3 seconds)
But when there are both - delay 3 seconds is incorrect

**Expected behaviour :** user messages should be processes every second and group messages - every 3 seconds

Thanks in advance! :)

**Comment by MihaZupan** [comment]
This is a problem with your test method - you are only enquing the private chat request after a group one finishes.

If you enqueue everything at once and only observe the times, you will get the expected results

https://gist.github.com/MihaZupan/b1798196cb792817c1b90935d385c592

**Comment by Ezergil** [comment]
> This is a problem with your test method - you are only enquing the private chat request after a group one finishes.
> 
> If you enqueue everything at once and only observe the times, you will get the expected results
> 
> https://gist.github.com/MihaZupan/b1798196cb792817c1b90935d385c592

Got it, thank you!

**Comment by Ezergil** [comment]
My bad, sorry :)

**Comment by MihaZupan** [comment]
All good, glad someone else's testing it
